export default {
    basic:[
        {key:'用户名',value:''},
        {key:'UID',value:''},
        {key:'等级',value:''},
        {key:'状态',value:''},
        {key:'注册时间',value:''},
        {key:'注册IP',value:''}
    ],
    level:[
        {key:'真实姓名',value:''},
        {key:'证件类型',value:''},
        {key:'证件号码',value:''},
        {key:'证件有效期',value:''},
        {key:'初级实名',value:''},
    ],
    asset:{
        columns:[
            {title:'币种',key:'currency',dataIndex:'assetCode'},
            {title:'总共',key:'total',dataIndex:'assetAmount'},
            {title:'可用',key:'usable',dataIndex:'assetUsable'},
            {title:'冻结',key:'lock',dataIndex:'assetLock'},
        ],
        data:{
            tokenList:[],
            cashList:[],
            coinList:[]
        }
    },
    kyc:{
        columns:[
            {title:'时间',key:'time',dataIndex:'updateDate'},
            {title:'类型',key:'type',dataIndex:'auditType'},
            {title:'审核状态',key:'audit',dataIndex:'auditStatus'},
            {title:'审核者',key:'audit_user',dataIndex:'auditUid'},
            {title:'备注',key:'remark',dataIndex:'auditMessage'},
        ],
        data:[]
    }
}